[build]
  publish = "./"
  functions = "./netlify/functions"
  command = "cd netlify/functions && npm install"

[[redirects]]
  from = "/auth-callback.html"
  to = "/.netlify/functions/discord-auth"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"